# Generated by Django 5.2.17 on 2026-09-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can view outstanding payments of the own corporation'), ('manage_sources', 'Can manage payment sources and app settings')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('model_label', models.CharField(help_text='The model holding one row per payment, as app_label.ModelName.', max_length=255, verbose_name='Model')),
                ('corporation_field', models.CharField(help_text='Field holding the EVE Corporation ID, e.g. corp_id or corporation__corporation_id.', max_length=255, verbose_name='Corporation ID field')),
                ('amount_field', models.CharField(help_text='Field holding the amount owed in ISK.', max_length=255, verbose_name='Amount field')),
                ('paid_field', models.CharField(help_text='Field that tells whether a payment has been made.', max_length=255, verbose_name='Paid field')),
                ('paid_mode', models.CharField(choices=[('true', 'Field is true'), ('not_empty', 'Field is not empty'), ('equals', 'Field equals value')], default='true', max_length=16, verbose_name='Paid when')),
                ('paid_value', models.CharField(blank=True, help_text='Only for "Field equals value": the value that means paid.', max_length=255, verbose_name='Paid value')),
                ('reason_template', models.CharField(blank=True, help_text='Reason to enter with the payment in game. Field names in braces are replaced by their values, with an optional format: {corp_id}/{month:02d}/{year}', max_length=255, verbose_name='Reason')),
                ('label_template', models.CharField(blank=True, help_text='What a row is for, shown next to the amount. Same placeholders as the reason, e.g. {month:02d}/{year}', max_length=255, verbose_name='Description')),
                ('date_field', models.CharField(blank=True, help_text='Optional date or datetime field; rows are sorted by it, newest first.', max_length=255, verbose_name='Date field')),
                ('pay_to', models.CharField(blank=True, help_text='Whom to send the ISK to, e.g. the holding Corporation.', max_length=255, verbose_name='Pay to')),
            ],
            options={
                'verbose_name': 'Payment source',
                'verbose_name_plural': 'Payment sources',
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InvoiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance', models.ForeignKey(blank=True, help_text='Only Corporations in this Alliance see their outstanding payments. Without an Alliance nobody sees anything.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eveonline.eveallianceinfo', verbose_name='Alliance')),
            ],
            options={
                'verbose_name': 'Configuration',
                'default_permissions': (),
            },
        ),
    ]
