# Generated by Django 5.2.17 on 2026-09-23 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_invoices', '0002_pay_to_corporation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('user_name', models.CharField(max_length=254, verbose_name='Marked by')),
                ('source_name', models.CharField(max_length=100, verbose_name='Source')),
                ('row_pk', models.CharField(max_length=64, verbose_name='Row')),
                ('corporation_id', models.BigIntegerField(verbose_name='Corporation ID')),
                ('corporation_name', models.CharField(blank=True, max_length=254, verbose_name='Corporation')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='Amount')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eos_invoices.paymentsource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment log entry',
                'verbose_name_plural': 'Payment log',
                'ordering': ['-created', '-pk'],
                'default_permissions': (),
            },
        ),
    ]
