# Generated by Django 5.2.17 on 2026-09-24 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_invoices', '0003_payment_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='paid_field',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='previous_value',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='reverted_at',
            field=models.DateTimeField(null=True, verbose_name='Undone'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='reverted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='reverted_by_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Undone by'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='written_value',
            field=models.JSONField(null=True),
        ),
    ]
