# Generated by Django 5.2.17 on 2026-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_invoices', '0004_payment_log_undo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsource',
            name='month_field',
            field=models.CharField(blank=True, help_text="Optional integer field (1-12) holding the row's month. While it equals the current month, the Reason is hidden - the amount owed for a month still in progress can still change.", max_length=255, verbose_name='Month field'),
        ),
    ]
