# Generated by Django 5.2.17 on 2026-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_invoices', '0005_payment_source_month_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsource',
            name='year_field',
            field=models.CharField(blank=True, help_text="Optional integer field holding the row's year, e.g. 2026. Used together with the Month field above - a month number alone cannot tell this year's row from the same month a year ago.", max_length=255, verbose_name='Year field'),
        ),
        migrations.AlterField(
            model_name='paymentsource',
            name='month_field',
            field=models.CharField(blank=True, help_text="Optional integer field (1-12) holding the row's month. Together with the Year field below, hides the Reason while the row is for the month still in progress - the amount owed for it can still change. Both fields are required for this; set alone, this one does nothing.", max_length=255, verbose_name='Month field'),
        ),
    ]
