# Generated by Django 5.2.17 on 2026-09-24 19:09

from django.db import migrations, models

PERMISSION_NAMES = {
    'basic_access': 'Can view the outstanding payments of their own Corporation',
    'manage_sources': (
        'Can view the payments of all Corporations, mark them as paid, read '
        'and undo the log, and manage payment sources and the Alliance'
    ),
}


def rename_permissions(apps, schema_editor):
    # Django only creates missing permissions after migrate, it never renames
    # existing ones - without this, installed sites kept the old wording.
    # Nothing to do on a fresh install: the rows do not exist yet.
    Permission = apps.get_model('auth', 'Permission')
    for codename, name in PERMISSION_NAMES.items():
        Permission.objects.filter(
            content_type__app_label='eos_invoices', codename=codename
        ).update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('eos_invoices', '0006_payment_source_year_field'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(rename_permissions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can view the outstanding payments of their own Corporation'), ('manage_sources', 'Can view the payments of all Corporations, mark them as paid, read and undo the log, and manage payment sources and the Alliance'))},
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='model_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentsource',
            name='date_field',
            field=models.CharField(blank=True, help_text='Optional date or datetime field, shown in the Date column. Without a Month and Year field, the Description column sorts by it; a source with too many rows for one page keeps its newest ones.', max_length=255, verbose_name='Date field'),
        ),
        migrations.AlterField(
            model_name='paymentsource',
            name='reason_template',
            field=models.CharField(blank=True, help_text='Reason to enter with the payment in game. Field names in braces are replaced by their values, e.g. {corp_id}/{month}/{year}; a format may follow a colon, as in {month:02d}. Use the exact form the receiving app matches payments against.', max_length=255, verbose_name='Reason'),
        ),
    ]
