# Generated by Django 5.2.17 on 2026-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_invoices', '0007_log_model_label_and_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsource',
            name='url',
            field=models.URLField(blank=True, help_text="Optional link to the app that manages these payments, shown on the source's name.", verbose_name='URL'),
        ),
    ]
